name: .NET Core Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest

    env:
      PUBLISH_LOCATION: "build/VS_BUILD_OUTPUT"
      PROJECT_LOCATION: "src/kepler.csproj"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    # Build the executable
    - name: Build Kepler executable
      run: dotnet build --output $env:PUBLISH_LOCATION $env:PROJECT_LOCATION