name: Interpreter Functionality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest

    env:
      PUBLISH_LOCATION: "build/VS_PUBLISH_OUTPUT"
      PROJECT_LOCATION: "src/kepler.csproj"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Generate buildtime
      run: scripts/generate_resources.bat continuous

    # Publish the executable
    - name: Build Kepler executable
      run: dotnet publish --output $env:PUBLISH_LOCATION $env:PROJECT_LOCATION
    
    # Run tests with a pass/fail exit
    - name: Do local tests
      run: scripts/run_tests_passfail.bat
